Organized notebook file, cleaned up directories, included example with tumor image
slaclab/xta pull request #2
Opened 2022-07-01 01:07 UTC by colinrec34

Cleaned up a lot of the file structuring, tried to make it as easy as possible to import a laser image and a dcm image for a clear and concise way to run the simulation. The example included is for 10000 particles travelled 0.25 meters from the cathode.

2022-08-16 22:33 UTC, nneveu requested changes
I haven't looked at the notebooks yet, but I left some small comments on the other files.

2022-08-16 22:33 UTC, nneveu commented on astra/astra-inputs/distgen.yaml
> +    value: 32.87
Was this the number we calculated? I thought we calculated 32 ps? This should be the 'sigma' value, not the FWHM, so a fraction of 32? It's not a huge problem for your paper/work/test case, but we should fix it before merging.

2022-08-16 22:33 UTC, nneveu commented on astra/astra-inputs/distgen.yaml
> +    value: 15
Is the beam size 15 mm or the whole picture size?

2022-08-16 22:33 UTC, nneveu commented on high_energy_opt/highe_opt.yaml
> -xopt:
Why was this deleted? It's an old optimization, but can go in a different folder?

2022-08-16 22:33 UTC, nneveu commented on high_energy_opt/highe_opt.yaml
> -xopt:
Same question for some of the older yaml files / dmd images?

2022-09-02 09:06 UTC, closed without merging

2022-09-02 09:07 UTC, colinrec34 commented
submitting refactored version in separate pull request